name: Upload image to GHCR

on:
  workflow_run:
    workflows: [Build and test]
    branches: [main, devel]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TARGET_PLATFORMS: amd64, arm64

jobs:
  build-and-upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Build and upload Docker image"
    runs-on: ["self-hosted"]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build Docker deploy container and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: ${{ env.TARGET_PLATFORMS }}
          target: deploy 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
